sudo: required

language: bash

addons:
  apt:
    packages:
      - docker-ce
      - grep

env:
  global:
    - IMAGE="swaggo-swag"
    - IMAGE_NAME="quay.io/hermsi1337/${IMAGE}"

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1
  - if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then docker login -u "${DOCKER_LOGIN_USER}" -p "${DOCKER_LOGIN_PASSWORD}" quay.io ; fi

script:
  - |
    #!/usr/bin/env bash

    set -xe

    get_latest_release() {
      curl --silent "https://api.github.com/repos/swaggo/swag/releases/latest" | # Get latest release from GitHub api
        grep '"tag_name":' |                                            # Get tag line
        sed -E 's/.*"([^"]+)".*/\1/' |                                  # Pluck JSON value
        cut -d 'v' -f 2
    }

    ALPINE_VERSIONS=("12")

    for ALPINE_VERSION in "${ALPINE_VERSIONS[@]}"; do
      PATCH_RELEASE_VERSION="$(get_latest_release)"
      MINOR_RELEASE_VERSION="${PATCH_RELEASE_VERSION%.*}"
      MAJOR_RELEASE_VERSION="${MINOR_RELEASE_VERSION%.*}"

      TAGS=("latest-alpine{ALPINE_VERSION}")
      TAGS+=("${PATCH_RELEASE_VERSION}")
      TAGS+=("${PATCH_RELEASE_VERSION}-alpine{ALPINE_VERSION}")
      TAGS+=("${MINOR_RELEASE_VERSION}")
      TAGS+=("${MINOR_RELEASE_VERSION}-alpine{ALPINE_VERSION}")
      TAGS+=("${MAJOR_RELEASE_VERSION}")
      TAGS+=("${MAJOR_RELEASE_VERSION}-alpine{ALPINE_VERSION}")

      docker build -t "${IMAGE_NAME}:latest" \
        --build-arg ALPINE_VERSION="${ALPINE_VERSION}" \
        --build-arg SWAGGO_SWAG_VERSION="${PATCH_RELEASE_VERSION}" \
      .

      for TAG in "${TAGS[@]}" ; do
        docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${TAG}"
      done

      if [[ "${TRAVIS_BRANCH}" == "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
        for TAG in "${TAGS[@]}" ; do
          docker push "${IMAGE_NAME}:${TAG}"
        done
      fi
    done